# Generated by Django 4.1.7 on 2023-04-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('can_delete_any_blog', 'Can delete any blog'), ('can_edit_any_blog', 'Can edit any blog')]},
        ),
    ]
