# Generated by Django 4.1.7 on 2023-03-26 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
    ]
