# Generated by Django 4.1.7 on 2023-04-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Accounts', '0003_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
